language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8
before_script: pep8 --max-line-length=100 .
script: nosetests --cover-package markdown --with-coverage tests
after_success:
  coveralls
